In [1]:
import numpy as np
from scipy.sparse import csr_matrix
  
sparseMatrix = csr_matrix((4, 4), dtype = np.int8).toarray()  
print(sparseMatrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
row = np.array([0, 0, 1, 1, 2, 1,3])
col = np.array([0, 1, 2, 0, 2, 2,2])
data = np.array([1, 4, 5, 8, 9, 6,6])
  
sparseMatrix = csr_matrix((data, (row, col)), shape = (4, 5)).toarray()    
print(sparseMatrix)

[[ 1  4  0  0  0]
 [ 8  0 11  0  0]
 [ 0  0  9  0  0]
 [ 0  0  6  0  0]]
